python3 -m albert.create_pretraining_data \
      --input_file=./mn_corpus/all.txt \
      --output_file=./mn_corpus/tf_records/all-maxseq-${max_seq_length}.tfrecord \
      --spm_model_file=./sp_models/30k-clean-mn.model \
      --vocab_file=./sp_models/30k-clean-mn.vocab \
      --do_lower_case=False \
      --max_seq_length=512 \
      --max_predictions_per_seq=20 \
      --masked_lm_prob=0.15 \
      --random_seed=12345 \
      --dupe_factor=5 \
      --do_whole_word_mask=False \
      --do_permutation=False \
      --favor_shorter_ngram=False \
      --random_next_sentence=False
